name: BlockyGen
main: com.blockycraft.blockygen.BlockyGen
version: 1.0
author: Bernardo Zukerman
description: Sistema de borda contínua e pré-carregamento de chunks para o BlockyCRAFT

commands:
  fill:
    description: Pré-geração dos chunks do mundo dentro da borda.
    usage: /fill [freq] [pad]
    permission: blockygen.fill
    permission-message: Você não tem permissão para usar este comando.
